# Generated by Django 3.1 on 2020-08-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Brend_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Product_Brend_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Фирма')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Произовдители',
            },
        ),
        migrations.CreateModel(
            name='Product_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product label',
                'verbose_name_plural': 'Products label',
            },
        ),
        migrations.CreateModel(
            name='Product_Specifications_Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=100, verbose_name='количество ядер')),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
            },
        ),
        migrations.CreateModel(
            name='Product_Specifications_RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=100, verbose_name='объем RAM')),
            ],
            options={
                'verbose_name': 'оперативка',
                'verbose_name_plural': 'оперативка',
            },
        ),
        migrations.CreateModel(
            name='Product_Specifications_Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=100, verbose_name='диагональ экрана')),
            ],
            options={
                'verbose_name': 'экран',
                'verbose_name_plural': 'экраны',
            },
        ),
        migrations.CreateModel(
            name='Digital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(default=None, null=True, upload_to='movies/', verbose_name='Фото')),
                ('price', models.PositiveIntegerField(default=0, help_text='указыжите сумму', verbose_name='Цена')),
                ('slug', models.SlugField(blank=True, max_length=150, verbose_name='Url')),
                ('model_name', models.ManyToManyField(max_length=100, to='digital_site.Product_Brend_Model')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_site.product_name', verbose_name='Phones')),
                ('processor', models.ManyToManyField(max_length=100, to='digital_site.Product_Specifications_Processor')),
                ('ram', models.ManyToManyField(max_length=100, to='digital_site.Product_Specifications_RAM')),
                ('screen', models.ManyToManyField(max_length=100, to='digital_site.Product_Specifications_Screen')),
                ('title', models.ManyToManyField(max_length=100, to='digital_site.Product_Brend_Name')),
            ],
            options={
                'verbose_name': 'Digital',
                'verbose_name_plural': 'Digitals',
            },
        ),
        migrations.CreateModel(
            name='CarShorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='movie_shots/', verbose_name='Pictures')),
                ('digital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_site.digital', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Short',
                'verbose_name_plural': 'Shorts',
            },
        ),
    ]
