# Generated by Django 3.1 on 2020-08-08 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital_site', '0002_carshorts_digital_product_brend_model_product_brend_name_product_name_product_specifications_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digital',
            name='name',
        ),
        migrations.AddField(
            model_name='digital',
            name='name',
            field=models.ManyToManyField(max_length=100, to='digital_site.Product_Name'),
        ),
        migrations.RemoveField(
            model_name='digital',
            name='title',
        ),
        migrations.AddField(
            model_name='digital',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digital_site.product_brend_name', verbose_name='Phones Title'),
        ),
    ]
