# Generated by Django 3.1 on 2020-08-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_site', '0003_auto_20200808_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digital',
            name='model_name',
        ),
        migrations.AddField(
            model_name='digital',
            name='model',
            field=models.ManyToManyField(max_length=100, to='digital_site.Product_Brend_Model'),
        ),
    ]
