# Generated by Django 3.1 on 2020-08-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_site', '0004_auto_20200809_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digital',
            old_name='model',
            new_name='model_digit',
        ),
    ]
