# Generated by Django 3.1 on 2020-08-09 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital_site', '0005_auto_20200809_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarShorts2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='movie_shots/', verbose_name='Pictures')),
                ('digital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_site.digital', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Short',
                'verbose_name_plural': 'Shorts',
            },
        ),
    ]
